In [78]:
from IPython.display import display, Markdown
import pickle
import private_function as pf
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

# Pretty display for notebooks
%matplotlib inline

# Ignore the warnings
import warnings
warnings.filterwarnings('ignore')

import gmaps
gmaps_api = pickle.load(open("./gmaps_api.pkl", "rb"))
gmaps.configure(api_key=gmaps_api)

In [61]:
def __getDfWithLoaction(df):
    # taken_at_timestamp is a unix timestamp - we add a column for the date-time
    time = '2018-01-01'
    df['taken_at_timestamp'] = df['taken_at_timestamp'].astype(int)
    df['time'] = pd.to_datetime(df['taken_at_timestamp'], unit='s')
    filtered = df[df['loc_id']!=0]
    filtered = filtered.sort_values(by=['time'], ascending=False)
    filtered = filtered[(filtered['time'] > time)]
    return filtered

def __makePopUpList(df):
    result = []
    for idx in range(len(df)):
        df_ = df.iloc[idx]
        result.append({
          "owner_name" : df_.owner_name,
          "is_video" : df_.is_video,
          "likes" : df_.likes,
          "time" : df_.time,
          "loc_name" : df_.loc_name,
          "location" : (df_.loc_lat, df_.loc_lon),
          "comment_cnt" : df_.comment_cnt,
          "video_view_count" : df_.video_view_count,
          "caption" : df_.caption,
          "tags" : ("#" + "#".join(df_.tags)) if df_.tags_cnt != 0 else None,
        })
    return result

def drawMarkerOnMap(df):
    df_ = __getDfWithLoaction(df)
    popUpList = __makePopUpList(df_)
    post_locations = [post['location'] for post in popUpList]

    info_box_template = """
    <dl>
    <dt>User</dt><dd>{owner_name}</dd>
    <dt>Is_Video</dt><dd>{is_video}</dd>
    <dt>Likes</dt><dd>{likes}</dd>
    <dt>Time</dt><dd>{time}</dd>
    <dt>Location Name</dt><dd>{loc_name}</dd>
    <dt>Comment Count</dt><dd>{comment_cnt}</dd>
    <dt>View</dt><dd>{video_view_count}</dd>
    <dt>Tags</dt><dd>{tags}</dd>
    </dl>
    """
    post_info = [info_box_template.format(**post) for post in popUpList]
    marker_layer = gmaps.marker_layer(post_locations, info_box_content=post_info)
    fig = gmaps.figure(center=(37.532600, 127.024612), zoom_level=10)
    fig.add_layer(marker_layer)
    
    print(len(post_info))
    return fig

In [2]:
df_li = pf.getAllDataFrame()

['직장인', '럽스타그램', '서울맛집', '먹스타그램', '친스타그램', '여행', '일상', '셀스타그램']

['seoul']

job.csv : 2213

insta_new_5.csv : 2136

insta_new_4.csv : 2148

insta_new_3.csv : 2172

insta_new_2.csv : 465

insta_new_1.csv : 2029

insta_new.csv : 2203

insta_train.csv : 5

insta_food_1.csv : 2217

insta_food.csv : 1911

food.csv : 1986

beer.csv : 1970

food_1.csv : 2068

food_2.csv : 2089

friend.csv : 1888

trip_1.csv : 1145

trip.csv : 2533

daily.csv : 2195

daily_2.csv : 785

daily_1.csv : 2312

selfie.csv : 2156

seongnam.csv : 960

seoul_2.csv : 19

seoul_1.csv : 960

incheon.csv : 960

seoul.csv : 880

yongin.csv : 960

gyeonggido.csv : 960

28


In [3]:
df_train = pf.makeOneTrainDf(df_li)

Df list length : 28
Df length changes after concat (if 0 means all datas are unique) : 0
Df length changes after concat (if 0 means all datas are unique) : 0
Df length changes after concat (if 0 means all datas are unique) : 1095
Df length changes after concat (if 0 means all datas are unique) : 411
Df length changes after concat (if 0 means all datas are unique) : 54
Df length changes after concat (if 0 means all datas are unique) : 131
Df length changes after concat (if 0 means all datas are unique) : 0
Df length changes after concat (if 0 means all datas are unique) : 35
Df length changes after concat (if 0 means all datas are unique) : 16
Df length changes after concat (if 0 means all datas are unique) : 75
Df length changes after concat (if 0 means all datas are unique) : 11
Df length changes after concat (if 0 means all datas are unique) : 42
Df length changes after concat (if 0 means all datas are unique) : 358
Df length changes after concat (if 0 means all datas are unique) : 1

In [4]:
train = pf.make_df_i_want(df_train)

In [5]:
counter = pf.get_counter(train)

In [6]:
counter.most_common()

[('', 3645),
 ('일상', 957),
 ('럽스타그램', 647),
 ('소통', 528),
 ('데일리', 487),
 ('먹스타그램', 482),
 ('daily', 443),
 ('좋아요', 438),
 ('맞팔', 376),
 ('셀스타그램', 364),
 ('남친이랑', 353),
 ('셀카', 344),
 ('선팔', 275),
 ('셀피', 265),
 ('일상스타그램', 265),
 ('먹방', 253),
 ('selfie', 248),
 ('팔로우', 239),
 ('맛스타그램', 236),
 ('데이트', 231),
 ('ootd', 200),
 ('인친', 184),
 ('직장인', 176),
 ('얼스타그램', 175),
 ('f4f', 172),
 ('럽스타', 168),
 ('선팔하면맞팔', 163),
 ('여행', 161),
 ('사랑해', 161),
 ('인스타그램', 150),
 ('instagood', 149),
 ('좋아요반사', 143),
 ('오오티디', 137),
 ('맥주스타그램', 133),
 ('맛집', 132),
 ('instagram', 130),
 ('데일리룩', 125),
 ('instadaily', 113),
 ('selca', 108),
 ('카페', 105),
 ('여행스타그램', 101),
 ('사진', 100),
 ('부산', 97),
 ('l4l', 92),
 ('친스타그램', 87),
 ('맥주', 87),
 ('follow', 86),
 ('소통해요', 86),
 ('여행에미치다', 86),
 ('fff', 86),
 ('술스타그램', 84),
 ('커플', 82),
 ('육아스타그램', 81),
 ('서울', 80),
 ('인스타', 78),
 ('첫줄', 76),
 ('love', 75),
 ('서울맛집', 75),
 ('데일리그램', 74),
 ('육아', 74),
 ('여', 71),
 ('육아소통', 70),
 ('맘스타그램', 70),
 ('dailylook', 68),
 

In [7]:
tag_count = 0
for tup in counter.most_common():
    tag_count += tup[1]
tag_count

45473

In [8]:
len(counter)

13962

In [9]:
frequentTags = [tag[0] for tag in counter.most_common()]

In [10]:
frequency = [tag[1] for tag in counter.most_common()]

In [11]:
y_pos = np.arange(len(frequentTags))

In [12]:
len(y_pos)

13962

In [13]:
train0 = train["tags_str"].values

In [15]:
train["duplicated_tag"] = train.tags.apply(lambda a: 1 if len(a) != len(set(a)) else 0) 

In [16]:
train_0 = train[train["duplicated_tag"] != 1]["tags_str"].values

In [74]:
duplicated_train = train[train["duplicated_tag"] == 1]

In [77]:
duplicated_train.head()

caption  comment_cnt  \
29  매운맛중독\n.\n.\n.\n#칠성포차 #마약찜닭 #응암오거리 #사라다 #먹스타그램...          1.0   
33  👉🏻옆으로 넘겨서 봐주세요!\n.\n✨8월 31일까지 피어싱,주얼리 10% 할인\n...          1.0   
44  5주간의 1인 경영 수업을 들으며,\n참 아직도 난 멀었구나 라는 생각이 들었다.\...          1.0   
46                        #20180831\n엄마 나도 칼퇴하고싶어..😣😭          3.0   
47  B6/8/31\n사이즈18.9cm 🎉안녕하세요 럭스갤러리 입니다^^ 언제나 최고의품...          2.0   

                                        first_comment                   id  \
29  #f4f#l4l#데일리#일상#좋아요#선팔#맞팔#팔로잉#팔로우#소통#팔로우#좋반#좋아...  1857799406611505102   
33  #맞팔해요#소통스타그램#인스타데일리#일상#일상소통#직장인룩#오피스룩#출근룩#직장인#...  1856574252839224506   
44  #셀피 #인스타 #인스타그램 #인스타데일리 #데일리 #데일리그램 #daily #일상...  1857893165093334700   
46  #회사원 #직장인 #대구 #휴무 #출근 #동성로 #회사 #사무실 #직딩 #주말 #불...  1857888664059646099   
47                                                NaN  1857893332034981244   

   is_video  likes     loc_id    loc_lat     loc_lon loc_name  \
29    False   17.0  236696750  37.584319  126.916065  서울시 은평구   
33    False    4.0          0   0.000000    0.000000      NaN   
44    False   15.0          0   0.000000    0.000000      NaN   
46    False   30.0          0   0.000000    0.000000      NaN   
47    False   23.0          0   0.000000    0.000000      NaN   

           ...                 owner_name    shortcode taken_at_timestamp  \
29         ...                 jjuuba_bba  BnIOrefAp_O         1535686969   
33         ...          a.things_official  BnD4HJHnkS6         1535540919   
44         ...             miracle_yu_sim  BnIj_14A66s         1535698145   
46         ...                 ha__yeongg  BnIi-V9gBCT         1535697609   
47         ...              lux__gallery2  BnIkCRWgw18         1535698165   

    video_view_count                                               tags  \
29               0.0  [칠성포차, 마약찜닭, 응암오거리, 사라다, 먹스타그램, 술스타그램, 매운맛중독, ...   
33               0.0  [맞팔해요, 소통스타그램, 인스타데일리, 일상, 일상소통, 직장인룩, 오피스룩, 출...   
44               0.0  [셀피, 인스타, 인스타그램, 인스타데일리, 데일리, 데일리그램, daily, 일상...   
46               0.0  [20180831, 회사원, 직장인, 대구, 휴무, 출근, 동성로, 회사, 사무실,...   
47               0.0  [daily, 강남, 데일리, 패션스타그램, 패션, 음식, 먹방, 맞팔, 연남동, ...   

   tags_cnt                                       caption_only  \
29       25               매운맛중독마약찜닭응암오거리사라다먹스타그램술스타그램매운맛중독맛집술집   
33       29  옆으로 넘겨서 봐주세요! . ✨8월 31일까지 피어싱,주얼리 10% 할인 ✨의류 잡...   
44       32  5주간의 1인 경영 수업을 들으며, 참 아직도 난 멀었구나 라는 생각이 들었다. 수...   
46       28                                         엄마나도칼퇴하고싶어   
47       31  B6831사이즈189cm안녕하세요럭스갤러리입니다언제나최고의품질하이퀄리티를약속드립니다...   

                                             tags_str duplicated_tag  \
29  칠성포차 마약찜닭 응암오거리 사라다 먹스타그램 술스타그램 매운맛중독 맛집 술집 f4...              1   
33  맞팔해요 소통스타그램 인스타데일리 일상 일상소통 직장인룩 오피스룩 출근룩 직장인 선...              1   
44  셀피 인스타 인스타그램 인스타데일리 데일리 데일리그램 daily 일상 소통 일상그램...              1   
46  20180831 회사원 직장인 대구 휴무 출근 동성로 회사 사무실 직딩 주말 불금 ...              1   
47  daily 강남 데일리 패션스타그램 패션 음식 먹방 맞팔 연남동 강남 가로수길 맘스...              1   

                  time  
29 2018-08-31 03:42:49  
33 2018-08-29 11:08:39  
44 2018-08-31 06:49:05  
46 2018-08-31 06:40:09  
47 2018-08-31 06:49:25  

[5 rows x 21 columns]

In [17]:
# from sklearn.model_selection import train_test_split
# X_train0, X_test0 = train_test_split(train0, test_size=0.33, random_state=42)

In [18]:
# len(X_train), len(X_test), len(train0)

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic %d:" % (topic_idx)) 
        print(" ".join([feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]])) 

# NMF is able to use tf-idf
tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(train_0)
tfidf_feature_names = tfidf_vectorizer.get_feature_names()

no_topics = 8

# Run NMF
# nmf = NMF(n_components=no_topics, random_state=1, alpha=.1, l1_ratio=.5, init='nndsvd').fit(tfidf)

In [20]:
def list_to_str(li):
    result = ""
    for tmp in li:
        result += tmp + " "
    return result

In [21]:
train["tags_str"] = train.tags.apply(list_to_str)

In [24]:
from sklearn.model_selection import GridSearchCV

In [52]:
n_topic = 13
alpha = 1
beta = 1
max_iter = 100
lda3 = LatentDirichletAllocation(n_components=n_topic, doc_topic_prior=alpha,\
                                topic_word_prior=beta, learning_method='online', max_iter=max_iter)
%time lda3.fit_transform(X_train)

CPU times: user 30min 16s, sys: 2min 52s, total: 33min 8s
Wall time: 33min 19s


array([[0.027461  , 0.02792705, 0.0279347 , ..., 0.02794116, 0.02817389,
        0.02793195],
       [0.02812787, 0.02737537, 0.02754929, ..., 0.58799014, 0.03456429,
        0.02738018],
       [0.05002464, 0.05211749, 0.05214528, ..., 0.05713624, 0.05109015,
        0.05213635],
       ...,
       [0.04081089, 0.04231758, 0.04151243, ..., 0.04052689, 0.04115761,
        0.04148665],
       [0.07692308, 0.07692308, 0.07692308, ..., 0.07692308, 0.07692308,
        0.07692308],
       [0.0641535 , 0.06583137, 0.06585193, ..., 0.06278073, 0.22994573,
        0.06584609]])

In [53]:
no_top_words = 20
display_topics(lda3, tf_feature_names, no_top_words)

Topic 0:
서울맛집 핫플레이스 강남맛집 JMT 맛스타그램 맛집투어 서울여행 강남 강남역 곱창 용산맛집 숙대맛집 남영동맛집 seoullife 맛집골목 후암동맛집 seoultravel youngsan 삼각지맛집 seouleats
Topic 1:
아침식사 장미 먹기 tumblr Korean 노랑 해물 라이프스타일 ASMR 가기 80s 돼지고기 Mukbang vaporwave pixelart FoodPorn 공식만찬 담홍색 KoreanFood KoreanAsmr
Topic 2:
asmr 피부관리 유튜브 mukbang 유튜버 eatingshow asmreating 피부고민 youtube asmrfood 병원 eatingsounds 베이킹클래스 보톡스 비건베이킹클래스 온새미로 veganbaking satisfying 쌀베이킹 자기관리
Topic 3:
먹스타그램 먹방 맛스타그램 맥주스타그램 맛집 술스타그램 food 점심 맥주 먹스타 foodstagram instafood 존맛 먹방스타그램 먹부림 맛스타 푸드스타그램 맛있다 음식 디저트
Topic 4:
MustafaCeceli nefesimceceli antalyamcfc MCVeMelekleri MCveMelekleri dilandeniz dilançiçekdeniz 햄스터 햄스타그램 골든햄스터 시리안햄스터 hamstagram syrianhamster goldenhamster 햄스타 hamsta hamster 기구필라테스 스피닝 핸드드립
Topic 5:
제주도 제주맛집 제주도맛집 f4follow 이벤트 서귀포맛집 제주여행 맥주스타그램 소통해요 선팔맞팔 제주 소통하자 제주맛집추천 제주도그램 제주서귀포맛집 제주도흑돼지맛집 제주도여행 아시안게임 로또 제주흑돼지
Topic 6:
일상 소통 맞팔 데일리 좋아요 선팔 셀스타그램 셀카 셀피 daily 일상스타그램 팔로우 먹스타그램 얼스타그램 선팔하면맞팔 럽스타그램 좋아요반사 selfie ootd 인친
Topic 7:
직장인 용인 사랑 취미 글스타그램 art 그림 성남 공감 글귀 일

In [49]:
n_topic = 15
alpha = 1
beta = 1
max_iter = 100
lda2 = LatentDirichletAllocation(n_components=n_topic, doc_topic_prior=alpha,\
                                topic_word_prior=beta, learning_method='online', max_iter=max_iter)
%time lda2.fit_transform(X_train)

CPU times: user 33min 54s, sys: 3min 17s, total: 37min 11s
Wall time: 37min 21s


array([[0.02624605, 0.02656986, 0.02655833, ..., 0.0293362 , 0.62659504,
        0.02656295],
       [0.02575063, 0.02605611, 0.0262146 , ..., 0.04627494, 0.06042683,
        0.02604773],
       [0.04933022, 0.05114366, 0.05105691, ..., 0.27039573, 0.0642345 ,
        0.05111056],
       ...,
       [0.03746286, 0.03772663, 0.03771456, ..., 0.03718444, 0.23320336,
        0.03772271],
       [0.06666667, 0.06666667, 0.06666667, ..., 0.06666667, 0.06666667,
        0.06666667],
       [0.05810899, 0.05903016, 0.05898609, ..., 0.0566412 , 0.05383643,
        0.05901384]])

In [51]:
no_top_words = 20
display_topics(lda2, tf_feature_names, no_top_words)

Topic 0:
서울맛집 강남맛집 강남역 곱창 강남 강남역맛집 역삼맛집 카드깡 역삼동맛집 신논현맛집 대치동맛집 곱창맛집 역삼동 서초맛집 서초동맛집 양재맛집 역삼역맛집 역삼역 양재역맛집 서초동곱창
Topic 1:
클래식 classic 슈트 awesome 꼼데 아크네 롱패딩 남자코트 겨울신상 시스템 구스다운 슬렉스 구로디지탈단지 하운드투스크체크 더블슈트 커팅진 핸드메이드코트 셋업 솔리드 터틀넥
Topic 2:
삼척맛집 인천카페 분당타투 시흥호빠 전북출장샵 잠실롯데 남자시계 의정부카페 영덕 동해맛집 부천호빠 삼척여행 대치동카페 길동마사지 부평술집 청라맛집 삼척데이트 철산호빠 인천호빠 부평호빠
Topic 3:
MustafaCeceli nefesimceceli antalyamcfc MCVeMelekleri MCveMelekleri 햄스터 햄스타그램 골든햄스터 시리안햄스터 syrianhamster hamster hamstagram hamsta 햄스타 goldenhamster 분당미술학원 아동미술 창의미술 분당맘 정자동창의미술
Topic 4:
제주도 제주맛집 제주도맛집 f4follow 서귀포맛집 제주여행 제주 소통해요 선팔맞팔 소통하자 제주맛집추천 제주도그램 제주서귀포맛집 맥주스타그램 제주도흑돼지맛집 제주도여행 제주흑돼지 제주도흑돼지 서귀포흑돼지맛집 서귀포흑돼지
Topic 5:
맥주스타그램 맥주 술스타그램 반려견 멍스타그램 beer 강아지 개스타그램 댕댕이 dog 고양이 냥스타그램 펫스타그램 beerstagram 수제맥주 cat 안주스타그램 견스타그램 dogstagram puppy
Topic 6:
럽스타그램 육아 육아소통 육아스타그램 육아맘 맘스타그램 도치맘 사랑해 젊줌마 딸스타그램 인스타베이비 애스타그램 직장인 아들스타그램 일상 아들맘 세젤귀 워킹맘 줌마그램 딸맘
Topic 7:
치느님 지름신 그램 못생김 카이 nini kimjongin 치킨 Lay Xiumin Chanyeol Chen EXO Baekhyun Kai Kyungsoo 김종인 Suho Sehun 거울샷
To

In [44]:
n_topic = 12
alpha = 1
beta = 1
max_iter = 100
lda1 = LatentDirichletAllocation(n_components=n_topic, doc_topic_prior=alpha,\
                                topic_word_prior=beta, learning_method='online', max_iter=max_iter)
%time lda1.fit_transform(X_train)

CPU times: user 28min 23s, sys: 2min 29s, total: 30min 52s
Wall time: 30min 58s


array([[0.02846244, 0.0286302 , 0.0284547 , ..., 0.02905464, 0.03246129,
        0.02871719],
       [0.03777424, 0.05374912, 0.02800077, ..., 0.60388787, 0.02775478,
        0.0282349 ],
       [0.05388883, 0.37355609, 0.05378705, ..., 0.06878303, 0.05252348,
        0.05307958],
       ...,
       [0.04232602, 0.04230973, 0.04249317, ..., 0.04161423, 0.04190817,
        0.04216267],
       [0.08333333, 0.08333333, 0.08333333, ..., 0.08333333, 0.08333333,
        0.08333333],
       [0.25329192, 0.06911207, 0.06908809, ..., 0.0665963 , 0.06731142,
        0.06856965]])

In [50]:
lda2.perplexity(X_train)

7687.474173442467

In [46]:
lda1.perplexity(X_train)

6820.714936895478

In [48]:
lda.perplexity(X_train), lda0.perplexity(X_train)

(5625.178948218268, 6259.854023980742)

In [55]:
from sklearn.externals import joblib
def saveModelObjectAsPickle(model, fileName):
    joblib.dump(model, fileName)

In [56]:
saveModelObjectAsPickle(lda, "lda_topic_8.pkl")
saveModelObjectAsPickle(lda0, "lda_topic_10.pkl")
saveModelObjectAsPickle(lda1, "lda_topic_12.pkl")
saveModelObjectAsPickle(lda2, "lda_topic_15.pkl")
saveModelObjectAsPickle(lda3, "lda_topic_13.pkl")

In [66]:
y_pred = lda1.transform(X_train)

In [68]:
y_pred = y_pred.argmax(axis=1)

In [72]:
len(train)

41240

In [70]:
len(y_pred)

34275

In [45]:
no_top_words = 20
display_topics(lda1, tf_feature_names, no_top_words)

Topic 0:
반려견 멍스타그램 강아지 개스타그램 댕댕이 dog 펫스타그램 견스타그램 dogstagram puppy 독스타그램 pet 말티즈 산책 푸들 instadog 포메 멍멍이 포메라니안 인스타독
Topic 1:
사랑 art 글스타그램 그림 공감 글귀 일러스트 생각 성남 직장 독서 책스타그램 직장인 감성 drawing 음악 작가 design 예술 끄적끄적
Topic 2:
용인 선물 취미 꽃스타그램 핸드메이드 꽃다발 생일선물 원데이클래스 귀걸이 인테리어소품 악세사리 flower 플로리스트 flowers 차스타그램 플라워레슨 답례품 선물추천 집들이선물 꽃바구니
Topic 3:
제주도 제주맛집 제주도맛집 f4follow 서귀포맛집 제주여행 제주 선팔맞팔 소통해요 소통하자 제주맛집추천 제주도그램 제주서귀포맛집 맥주스타그램 제주도흑돼지맛집 제주도여행 제주흑돼지 제주도흑돼지 서귀포흑돼지맛집 서귀포흑돼지
Topic 4:
남친이랑 서울맛집 데이트 강남맛집 부산맛집 대구맛집 강남역 곱창 강남역맛집 강남 역삼맛집 카드깡 역삼동맛집 신논현맛집 대치동맛집 곱창맛집 역삼동 서초맛집 서초동맛집 양재맛집
Topic 5:
일상 소통 데일리 맞팔 좋아요 선팔 셀스타그램 셀카 셀피 daily 일상스타그램 팔로우 먹스타그램 럽스타그램 얼스타그램 선팔하면맞팔 좋아요반사 selfie ootd 인친
Topic 6:
발렌티노 발렌시아가 팔찌 나이키오프화이트 몽블랑 막스마라 불가리 오프화이트 겐조 보태가베네타 남여 구찌로퍼 슈프림 구찌블로퍼 강남카페 발렌시아가트리플s 루이비통스니커즈 구찌스니커즈 베트멍 발렌시아가스피드러너
Topic 7:
아이폰케이스 폰케이스 커플케이스 아이폰7케이스 아이폰x케이스 아이폰8케이스 갤럭시케이스 노트8케이스 핸드폰케이스 케이스 asmr 노트9케이스 갤럭시s9케이스 갤럭시s9플러스케이스 아이폰6케이스 갤럭시s8케이스 피부관리 아이폰8 아이폰6s케이스 아이폰7플러스케이스
Topic 8:
먹스타그램 맛스타그램 먹방 맥주스타그램 맛집 술스타그램 food 점심 맥주 먹스타 fo

In [42]:
n_topic = 10
alpha = 1
beta = 1
max_iter = 100
lda0 = LatentDirichletAllocation(n_components=n_topic, doc_topic_prior=alpha,\
                                topic_word_prior=beta, learning_method='online', max_iter=max_iter)
%time lda0.fit_transform(X_train)

CPU times: user 24min 43s, sys: 2min 4s, total: 26min 48s
Wall time: 26min 51s


array([[0.03034193, 0.03009292, 0.72674743, ..., 0.03009416, 0.02990435,
        0.02995341],
       [0.02898188, 0.02928155, 0.05213581, ..., 0.03110121, 0.02927703,
        0.05513075],
       [0.05782456, 0.06067132, 0.09648807, ..., 0.06066269, 0.06028198,
        0.40280782],
       ...,
       [0.0450813 , 0.04566523, 0.27892614, ..., 0.04570353, 0.04561407,
        0.045772  ],
       [0.1       , 0.1       , 0.1       , ..., 0.1       , 0.1       ,
        0.1       ],
       [0.07771726, 0.08053127, 0.07323953, ..., 0.08048504, 0.08015895,
        0.0797431 ]])

In [43]:
no_top_words = 20
display_topics(lda0, tf_feature_names, no_top_words)

Topic 0:
맥주스타그램 여행에미치다 여행 여행스타그램 남친이랑 travel 맥주 휴가 korea 술스타그램 beer photography seoul 여름 일본 여름휴가 trip 바다 한국 풍경
Topic 1:
bts kpop 방탄소년단 jungkook jimin jhope jin suga army taehyung bangtanboys rm BTS jeonjungkook kimtaehyung bangtansonyeondan parkjimin yoongi exo namjoon
Topic 2:
일상 소통 데일리 맞팔 좋아요 선팔 셀스타그램 셀카 셀피 daily 일상스타그램 팔로우 먹스타그램 얼스타그램 선팔하면맞팔 럽스타그램 좋아요반사 selfie ootd 인친
Topic 3:
먹스타그램 맛스타그램 먹방 맛집 서울맛집 남친이랑 food 점심 먹스타 데이트 술스타그램 foodstagram instafood 일상 디저트 먹방스타그램 JMT 맛스타 존맛 먹부림
Topic 4:
럽스타그램 육아 육아소통 육아스타그램 육아맘 맘스타그램 도치맘 사랑해 일상 젊줌마 딸스타그램 직장인 인스타베이비 애스타그램 아들스타그램 아들맘 세젤귀 워킹맘 줌마그램 딸맘
Topic 5:
카드깡 서울맛집 남친이랑 모바일문화상품권 상품권현금화 신용카드현금화 굿핀 해피머니 컬쳐랜드 일수대출 신용카드대출 모바 용인 신촌맛집 art 그림 초현당 성남 일러스트 팔로잉
Topic 6:
반려견 멍스타그램 강아지 개스타그램 댕댕이 dog 고양이 웨딩 냥스타그램 펫스타그램 결혼 예신 샤넬 결혼준비 구찌 웨딩촬영 견스타그램 dogstagram 루이비통 럽스타그램
Topic 7:
아이폰케이스 폰케이스 커플케이스 아이폰7케이스 아이폰x케이스 아이폰8케이스 갤럭시케이스 노트8케이스 피부관리 MustafaCeceli nefesimceceli 핸드폰케이스 케이스 노트9케이스 antalyamcfc 갤럭시s9케이스 아이폰8 갤럭시s9플러스케이스 아이폰6케이스 갤럭시s8케이스
Topic 8:
대전맛집 서울맛집 부산맛집 대구맛집

In [73]:
len(train_0)

34275

In [29]:
# vectorizer the features
# no_features = 1000

cnt_vectorizer = CountVectorizer(lowercase=False)
X_train = cnt_vectorizer.fit_transform(train_0)

# hyper parameter
n_topic = 8
alpha = 1
beta = 1
max_iter = 100

# train the model

lda = LatentDirichletAllocation(n_components=n_topic, doc_topic_prior=alpha,\
                                topic_word_prior=beta, learning_method='online', max_iter=max_iter)

# lda = LatentDirichletAllocation(doc_topic_prior=alpha, topic_word_prior=beta, learning_method='online',\)
%time lda.fit_transform(X_train)
# param_range = np.arange(5, 16)
# max_iter = [10, 100]
# param_grid = {'n_components': param_range, 'max_iter': max_iter }

# gs = GridSearchCV(estimator=lda, param_grid=param_grid, cv=10, n_jobs=4)
# %time gs = gs.fit(X_train)

CPU times: user 21min 3s, sys: 1min 10s, total: 22min 13s
Wall time: 22min 17s


array([[0.03143017, 0.76632969, 0.03146694, ..., 0.03142455, 0.03112262,
        0.03149344],
       [0.03258212, 0.07030531, 0.03083171, ..., 0.03069922, 0.03174339,
        0.04768798],
       [0.06747264, 0.07432164, 0.0678736 , ..., 0.06663124, 0.06528969,
        0.06574688],
       ...,
       [0.04989778, 0.30130412, 0.05004762, ..., 0.07608055, 0.06239624,
        0.08685205],
       [0.125     , 0.125     , 0.125     , ..., 0.125     , 0.125     ,
        0.125     ],
       [0.09928389, 0.08667791, 0.10025087, ..., 0.0982733 , 0.09624484,
        0.32967683]])

In [30]:
tf_feature_names = cnt_vectorizer.get_feature_names()

In [31]:
test = [
    "와 힘드네..",
    "세절맛..",
    "죽겠당"
]

In [32]:
test_ = cnt_vectorizer.transform(test)

In [40]:
doc_topic_dist_unnormalized = np.matrix(lda.transform(test_))

# normalize the distribution (only needed if you want to work with the probabilities)
doc_topic_dist = doc_topic_dist_unnormalized/doc_topic_dist_unnormalized.sum(axis=1)

In [36]:
doc_topic_dist.argmax(axis=1)

matrix([[6],
        [0],
        [0],
        [0]])

In [41]:
no_top_words = 20
display_topics(lda, tf_feature_names, no_top_words)

Topic 0:
선물 취미 bts 그림 kpop art 방탄소년단 꽃스타그램 핸드메이드 일러스트 성남 꽃다발 행복하자 jungkook jimin 원데이클래스 drawing jhope 생일선물 세종
Topic 1:
일상 소통 데일리 맞팔 좋아요 선팔 셀스타그램 셀카 셀피 daily 일상스타그램 팔로우 먹스타그램 얼스타그램 선팔하면맞팔 럽스타그램 좋아요반사 selfie ootd 인친
Topic 2:
서울맛집 강남맛집 강남역 곱창 강남 강남역맛집 역삼맛집 카드깡 역삼동맛집 신논현맛집 대치동맛집 맛스타그램 곱창맛집 역삼동 서초맛집 서초동맛집 양재맛집 역삼역맛집 역삼역 양재역맛집
Topic 3:
여행에미치다 여행 여행스타그램 travel 휴가 다이어트 korea photography 커플 사랑 여름 직장인 seoul 일본 운동하는여자 여름휴가 럽스타그램 바다 trip 다이어터
Topic 4:
럽스타그램 육아 육아소통 육아스타그램 육아맘 맘스타그램 도치맘 사랑해 젊줌마 딸스타그램 인스타베이비 일상 애스타그램 아들스타그램 직장인 아들맘 세젤귀 워킹맘 줌마그램 딸맘
Topic 5:
제주도 선팔맞팔 제주맛집 제주도맛집 부산맛집 소통해요 f4follow 소통하자 서울맛집 대구맛집 서귀포맛집 제주여행 제주맛집추천 제주도그램 맥주스타그램 제주 제주서귀포맛집 대전맛집 맛집탐방 서면맛집
Topic 6:
남친이랑 맥주스타그램 술스타그램 맥주 데이트 beer 수제맥주 주말 소주 치맥 치킨 혼술 이벤트 맥주한잔 영화 소맥 아시안게임 beerstagram 술안주 남친
Topic 7:
먹스타그램 먹방 맛스타그램 맛집 food 서울맛집 점심 먹스타 일상 instafood foodstagram 디저트 JMT 핫플레이스 먹부림 반려견 음식 먹방스타그램 맛스타 푸드스타그램


In [ ]:
# predict topics for test data
X_test = tf_vectorizer.transform(test)
doc_topic_dist_unnormalized = np.matrix(lda.transform(X_test))

# normalize the distribution (only needed if you want to work with the probabilities)
doc_topic_dist = doc_topic_dist_unnormalized/doc_topic_dist_unnormalized.sum(axis=1)